insert into public.projects
  (slug, sort_order, title, tagline, category, tags,
   thumbnail_url, is_featured,
   hero_image_url,
   client, services, deliverables, year, duration, role, project_url,
   overview, challenge, approach, outcome,
   gallery, stats,
   testimonial_quote, testimonial_author, testimonial_role,
   related_slugs, meta_title, meta_description)
values
-- 01
( 'kinetic-brand-reveal',
  1,
  'Kinetic Brand Reveal',
  'Motion identity system for a global fintech launch',
  'Motion',
  array['Motion Graphics','Brand Animation','3D','Sound Design'],
  'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
  true,
  'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1600&q=90',
  'Nexus Finance',
  array['Motion Design','Brand Strategy','Sound Design'],
  array['60s Hero Film','Logo Animation Pack','Social Motion Kit'],
  2024, '8 weeks', 'Creative Director & Lead Animator', null,
  'Nexus Finance needed a brand reveal film to anchor their Series B launch event. The brief called for something that communicated trust and innovation simultaneously — two qualities rarely coexist in fintech visuals.',
  'The core challenge was translating abstract financial concepts into kinetic, emotionally resonant motion — without falling back on tired stock-market clichés.',
  'We built a custom particle system in Cinema 4D, choreographed to a bespoke sound score. Each particle represented a data transaction, coalescing into the Nexus logotype over 60 seconds.',
  'The reveal film was played live to 1,200 investors. Nexus raised $40M in their Series B within three weeks. The motion kit was adopted across all brand touchpoints.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=85","caption":"Particle system development — Cinema 4D","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=85","caption":"Storyboard frames","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=85","caption":"Final logo lock-up frame","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=85","caption":"Event screening setup","full_width":true}
  ]'::jsonb,
  '[{"value":"$40M","label":"Raised Post-Launch"},{"value":"1,200","label":"Live Audience"},{"value":"8","label":"Weeks to Delivery"}]'::jsonb,
  'The particle reveal was unlike anything we had seen in fintech. It gave our brand a soul.',
  'Daniel Marsh', 'CMO, Nexus Finance',
  array['frame-rate-documentary','silent-city-campaign'],
  'Kinetic Brand Reveal — Nexus Finance | Motion Studio',
  'A 60-second brand reveal film using particle systems and bespoke sound design for a Series B fintech launch.'
),
-- 02
( 'frame-rate-documentary',
  2,
  'Frame Rate Documentary',
  'Feature-length film about the last analogue film processors',
  'Film',
  array['Documentary','Cinematography','Color Grading','Narrative Editing'],
  'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=800&q=80',
  true,
  'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=1600&q=90',
  'Aperture Foundation',
  array['Direction','Cinematography','Post-Production'],
  array['90-min Feature Film','Festival Cut (72min)','Theatrical Poster'],
  2024, '14 months', 'Director & Editor', 'https://example.com',
  'A feature documentary following three of the last analogue film processors in the world across Tokyo, Prague, and Buenos Aires.',
  'Making a technically complex documentary on a tight budget while maintaining cinematic quality demanded every creative shortcut we could engineer.',
  'We shot entirely on 16mm and Super-8, scanning at 4K. The rough texture became a visual metaphor for the medium''s fragility — no post-production cleanup, every scratch kept intentional.',
  'Selected for 14 international festivals. Winner of Best Documentary at the Berlin Independent Film Awards 2024.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1567593810070-7a3d471af022?w=1200&q=85","caption":"On location — Tokyo Film Lab","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=85","caption":"Colour grade reference frames","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=85","caption":"Editing suite — Berlin","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&q=85","caption":"Final theatrical poster","full_width":true}
  ]'::jsonb,
  '[{"value":"14","label":"Festival Selections"},{"value":"3","label":"Countries Filmed"},{"value":"90","label":"Minutes Runtime"}]'::jsonb,
  'The most honest film about our craft made in a decade.',
  'Ingrid Vogt', 'Director, Aperture Foundation',
  array['kinetic-brand-reveal','silent-city-campaign'],
  'Frame Rate Documentary | Orisa Motion Studio',
  'A feature documentary about the last analogue film processors in Tokyo, Prague, and Buenos Aires — shot on 16mm.'
),
-- 03
( 'silent-city-campaign',
  3,
  'Silent City Campaign',
  'Multi-platform motion campaign for urban mental health awareness',
  'Campaign',
  array['Campaign','Motion Graphics','Social Content','Direction'],
  'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
  false,
  'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1600&q=90',
  'Urban Minds NGO',
  array['Creative Direction','Motion Design','Social Strategy'],
  array['Hero Film (90s)','12x Social Reels','OOH Motion Graphics'],
  2023, '10 weeks', 'Creative Director', null,
  'Urban Minds NGO needed a campaign that broke through social media fatigue to start real conversations about urban loneliness — without resorting to shock tactics.',
  'The challenge: make silence visible. Most motion work relies on energy and momentum; this project demanded restraint.',
  'We shot 48 hours of b-roll in four cities with no dialogue. The edit used long-form static shots — 15 to 30 seconds each — punctuated by a single sound design note. Deeply uncomfortable. Deeply effective.',
  '4.2M organic views across platforms in the first week. Campaign adopted by 9 city councils as official mental health awareness material.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1200&q=85","caption":"Campaign stills — London","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&q=85","caption":"Social reel cut — New York","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=85","caption":"OOH placement mockup","full_width":false}
  ]'::jsonb,
  '[{"value":"4.2M","label":"Organic Views (Week 1)"},{"value":"9","label":"City Council Adoptions"},{"value":"4","label":"Cities Filmed"}]'::jsonb,
  'This campaign made our board cry. That was the brief.',
  'Amara Osei', 'Executive Director, Urban Minds NGO',
  array['kinetic-brand-reveal','haptic-product-launch'],
  'Silent City Campaign — Urban Minds NGO | Motion Studio',
  'A multi-platform motion campaign tackling urban loneliness through the power of cinematic silence.'
),
-- 04
( 'haptic-product-launch',
  4,
  'Haptic Product Launch',
  '3D product visualisation and launch film for a wearable tech brand',
  '3D',
  array['3D Visualisation','Product Film','CGI','UI Animation'],
  'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
  false,
  'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1600&q=90',
  'Haptic Labs',
  array['3D Modelling','Product Animation','CGI Compositing'],
  array['60s Launch Film','Product 360 Turntable','Website Hero Loop'],
  2024, '6 weeks', 'Lead 3D Artist', 'https://example.com',
  'Haptic Labs launched their second-generation haptic feedback wearable with a zero-gravity product film showing the device in photorealistic 3D.',
  'Recreating tactile sensation — the core product promise — through a purely visual medium, while achieving photo-real CGI quality on a mid-size budget.',
  'We built every component of the device in Cinema 4D with sub-surface scattering shaders for the silicone components. The launch film intercuts live footage of hands with CGI device close-ups seamlessly.',
  'Product page conversion rate increased 34% in the first month post-launch. Film used in Series A investor deck.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=1200&q=85","caption":"CGI render — product wireframe","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1585241645927-c7a8e5840c42?w=800&q=85","caption":"Live / CGI composite reference","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=800&q=85","caption":"Final product hero shot","full_width":false}
  ]'::jsonb,
  '[{"value":"34%","label":"Conversion Rate Increase"},{"value":"60s","label":"Launch Film Runtime"},{"value":"3","label":"Platform Deliverables"}]'::jsonb,
  'Our product has never looked this good — not even in real life.',
  'Marcus Lee', 'Founder & CEO, Haptic Labs',
  array['kinetic-brand-reveal','silent-city-campaign'],
  'Haptic Product Launch — Haptic Labs | Motion Studio',
  'Photorealistic 3D product visualisation and launch film for a haptic wearable brand.'
),
-- 05
( 'volta-identity-system',
  5,
  'Volta Identity System',
  'Full brand identity and motion guidelines for a clean energy startup',
  'Branding',
  array['Brand Identity','Motion Guidelines','Logo Animation','Typography'],
  'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
  false,
  'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1600&q=90',
  'Volta Energy',
  array['Brand Identity','Motion Design','Design System'],
  array['Brand Guidelines PDF','Logo Animation Library','Motion Principles Doc','Icon Set'],
  2023, '12 weeks', 'Brand & Motion Director', 'https://example.com',
  'Volta Energy, a clean energy startup, needed a brand identity flexible enough to work from pitch deck to billboard — and a motion language to match their kinetic visual world.',
  'Clean energy brands default to green clichés. The challenge was to create something that felt like a serious technology company, not an environmental charity.',
  'We anchored the identity in a single geometric form — a volt arc — that became the basis of the logo, icon set, and motion transitions. Every animation in the system derives from the same 240ms easing curve.',
  'Brand adopted across 40+ materials within 8 weeks. Volta raised £12M seed round 6 months post-rebrand.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=1200&q=85","caption":"Identity system overview","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=85","caption":"Logo animation keyframes","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=85","caption":"Motion principles doc spread","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1542621334-a254cf47733d?w=1200&q=85","caption":"Billboard and environmental applications","full_width":true}
  ]'::jsonb,
  '[{"value":"40+","label":"Brand Touchpoints"},{"value":"£12M","label":"Raised Post-Rebrand"},{"value":"8","label":"Weeks to Full Rollout"}]'::jsonb,
  'They understood our world before we explained it. The brand feels like us — bold, precise, electric.',
  'Priya Nair', 'Co-Founder & CEO, Volta Energy',
  array['kinetic-brand-reveal','frame-rate-documentary'],
  'Volta Identity System | Motion Studio',
  'Full brand identity and motion guidelines for a clean energy startup — from logo to billboard.'
),
-- 06
( 'echo-title-sequence',
  6,
  'Echo Title Sequence',
  'Opening title sequence for a Netflix original thriller series',
  'Film',
  array['Title Sequence','Typography Motion','Compositing','Sound Design'],
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80',
  false,
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1600&q=90',
  'Netflix (via production company)',
  array['Title Design','Motion Graphics','Compositing','Sound'],
  array['90s Title Sequence','Episodic Variations (x8)','Credit Templates'],
  2024, '5 weeks', 'Title Sequence Designer', null,
  'Designed the opening title sequence for Echo, a Netflix original psychological thriller. The brief called for something that would plant unease in the viewer before a single line of dialogue.',
  'A title sequence must reward repeat viewings — the challenge was layering meaning without telegraphing the plot.',
  'We built the sequence around distorted typography revealed through a water-surface refraction simulation. Hidden words appear in the ripples on second viewing. Each episode gets a unique refraction pattern derived from a keyword in that episode.',
  'Sequence became widely discussed online for its hidden details. The typographic reveal technique was shortlisted for an SXSW title design award.',
  '[
    {"type":"image","url":"https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=1200&q=85","caption":"Title frame — principal typography","full_width":true},
    {"type":"image","url":"https://images.unsplash.com/photo-1542652694-40abf526446e?w=800&q=85","caption":"Water refraction simulation frames","full_width":false},
    {"type":"image","url":"https://images.unsplash.com/photo-1574717025058-2f8737d2e2b7?w=800&q=85","caption":"Hidden words overlay — second viewing","full_width":false}
  ]'::jsonb,
  '[{"value":"8","label":"Episodic Variations"},{"value":"90s","label":"Sequence Length"},{"value":"1","label":"SXSW Shortlist"}]'::jsonb,
  'We asked for unsettling. We got a masterpiece.',
  'Rachel Torres', 'Executive Producer, Echo',
  array['frame-rate-documentary','kinetic-brand-reveal'],
  'Echo Title Sequence — Netflix Original | Motion Studio',
  'Opening title sequence for a Netflix original thriller, featuring distorted typography and hidden narrative layers.'
);
